<a href="https://colab.research.google.com/github/mgodfrey1294/PyTorch-Tutorial-YouTube/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors


*   A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.
*   Similar to Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).
*   default data type of float32.
*   More suitable for deep learning than a numpy array





In [1]:
import torch
import numpy as np

# LISTS

In [3]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# NUMPY ARRAYS

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.4260338 , 0.44075447, 0.44275298, 0.28455889],
       [0.77412143, 0.93475664, 0.93382179, 0.73036203],
       [0.55573447, 0.34294393, 0.26138305, 0.5939121 ]])

In [6]:
np1.dtype

dtype('float64')

# TENSORS

In [17]:
tensor_2d = torch.randn(3,4)
tensor_2d
# tensor_2d.dtype

tensor([[ 0.2119, -0.4209,  0.9034, -0.1635],
        [ 1.0440, -0.8712,  1.5054, -0.0310],
        [-0.2258,  2.1068, -0.5349,  0.1768]])

In [8]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.4260, 0.4408, 0.4428, 0.2846],
        [0.7741, 0.9348, 0.9338, 0.7304],
        [0.5557, 0.3429, 0.2614, 0.5939]], dtype=torch.float64)